services:
  frontend:
    build:
      context: ./frontend
    ports:
      # - "5173:5173"
      - 4200:4200
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./backend/files:/app/files
      - ./backend/db:/app/db
      - ./backend/chat_sessions:/app/chat_sessions
    command: poetry run uvicorn chatbot:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
  node_modules: