services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/pdfs:/app/pdfs
      - ./backend/db:/app/db
      - ./backend/chat_sessions:/app/chat_sessions
    command: poetry run uvicorn chatbot:app --reload --host 0.0.0.0 --port 8000