FROM python:3.11.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install the openai-whisper package
RUN pip install openai-whisper

# This image now has openai-whisper installed