FROM python:3.11.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install the openai-whisper & unstructured package
RUN pip install unstructured[all-docs] openai-whisper
